version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_WEBPACK_USEPOLLING=1
      - WATCHPACK_POLLING=true
    command: sh -c "npm run dev"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html
      - /var/www/html/vendor
    environment:
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
    user: "www-data:www-data"
    command: >
      bash -c "
        mkdir -p /var/www/html/database &&
        touch /var/www/html/database/database.sqlite &&
        chmod 777 /var/www/html/database &&
        chmod 666 /var/www/html/database/database.sqlite &&
        composer install &&
        php artisan migrate --force &&
        php artisan serve --host=0.0.0.0 --port=8000
      "

volumes:
  backend_sqlite: